dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: h/KmC4xOZE5rVQk+NZuKQbkPeUf1SVZY5J7GsUunQRrJTV0Rd0a7NO8O9DIe/6ud5ZCk7+m3A7XiViA8yKwiLzeUPVxuDYFfljTIUAdYQR0c0UhWRvRtcJ6ZRLuYz9RFuND2nf2bD0Ohd9jYgO5u1IC0I+IkIJmmV0ue58Zv+YpkKz7hQCJ8hw3V6ojhGbV6x9MdTTkoEhTb8F6gYlzzmpxOnHoEmNZd2xH865k+O085nV2uoPpcHqRRP5aS2xC4q7kt8RRfoTczNoPgABrNNVbhelY+OGmLTHjVH4gsn0AS89VDGrMK3OYI7pBy/s+5VJX03oNzPHrGPVdDdoMn/B/FAB5krE75wkijcLd3+/9k7IcyKow9W/UWnAcDmNGhQR8+qoMZgQ0Vjc26XLBJ8aqKO4aWHcAazEJB5ovQNwR/g00w5O98GRfUGQvQjRFcJSb5T8csmwMCuaYs37RIjYBREcvOODfu+x4wLQf8UDmqI/JrB4QGDQSCESKI8P+sR5TL9wsm1tnIgfNdzhvgpa/X2xmEgMGrhQUp+9VdVnrY7ebvLgAYEEtgAxM3NBhC6bzCWfE1Yq0+fIFu/8KM7IapBCmx6PwGX5QGyGU7QqEi0CgfYy4iLZckZEJpz6XNEHtlG7fyyuW9s6TlJKeMObLvwfUucpiE5v2ZG7XLx3Y=
  - secure: GLuX33PSlAcCS/y1afemN72z/KG8adBx5sjxqSOQjq3oIwSTJIkQHllRBhW1X73XfqU5At6jfoq7hjSsYyDjXcVpi2tWK4TFZUlZAHdlJgh3vh0x2sOTGI/kk+YLu7w9t7E9HvQnKWFDDYxCai+XirFxDL6XbyDABx32zSALkmZNBdIRvEaLU/SO1QLadHhywJrs7vP5lwmCJa67QMxqgXIw1BXwzSFMKJFvBrT2ng2yoB54bkNji1ZlIk/eqJolybTnkd5fqliLb5QcZWGT5B8gPPFC860/4ckY5A0rE1q2CaQmTPKUngFDV3O79KOOn2yysWYFT0zmsjRyjvgpMId8zwqZuZmgTxrYhDvSvyzzZuPsINt/IFyetQeRvVNYxITPcv7CI/zU/tVFp4qP3GuWRGpcbh5tlAbwzKdLBPMqWba7XRtpD6L1LdDV199H4Nb5xWn6fb47vJ/OZJwIpDmriQkpWJsieH2Su4zJ37OEcJEYdldWCGq65MJqVYgPc1Vh7lrghEKI7Shw0a4mWT7/3irI0InxGANzHKWXSbiIuH0M82hfCOKys6pI4BGkaKz+gCG0QS8tHh1MR97QJx72NVj8wDhGa60qN7TR0dzdjD5OpX+2KjAjd3Sr145x6SSqPTAeZFj11+WywJGoiwNpEMYZAnnwKZWWGC5W8Yo=
  - secure: qBmpLQbBtrpfHiWBnCy/2ee+ICBPfIGTNipCv6w1GZ9h2jH8MWsPz5Kd+NFWJqCFgrbQ8b7PfGCyDLkGg8Llr5t/q8IOBzlwxKD0QrK2exSM4lgfVh5qv8SpKMCqMPO2HApoiIi4KJYqJsaQ+fHGWWHtaBT7KsINw1CqfuAkBzWdKjQL+AbPuwCZ3swg2cGWrJaDYYC17hDQ4s/l5EpESF5I9R3xn1xw+rNfjqUa0EC+yuCuZx6WA7xaPkxarYfFI71l/Ry43zmJbgo4Fj4BzDgS5z6nadrTREdiCpEAxOJZxeZIIRjNnvX9UMN7j/wYa1HuZwhfZ9xj3bdBq6PgA4DpzV3xpCfUJkVwLzHYVwLcPJRWzkHXJJH8g6UVdDc++5xHHPGD7ijmW4tB6gjaj//XQU+CdtC99ybFhR/2pACJVT7aWByVkmKWmdVDdcpjKoc6/a8IwwMGE63hrk4UDWiPtT0Tzh2+32Chm09r9EWzkViqirBfdNsLgWVvBBsxWgFJo84Jy/Vfr9On5a0IHvocJSwts/fIsEzYCrbCzpgJNM8f3tfkbKedmuKZVlgcKfxF5wK4Ql64tCOHlgTgoOqr/ReCMpLsLbIZzBGoiiyU7c1rfbOdXgzOswTDxGJ0L83C+HI/7k4Kn9C+YGMtVNsbiB/5EWbp8g41iRJfNPM=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
