language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: amn7NhVNbz4yYmnj5sOl30SeC/R0nlI6pzoXTipGFQyJfgk3hhi450/1N05tqXOrf6qFVuxnpCN24olWOHSRSD2bfmN35YZzfLeNyov31XYmzEBwCWphM56cNxO3AOb1TZuICMXE5EbynrZK3C+vq3NMAMjSHyQ9LdZCuHc1cSaoG8H6Ti7IeOc7DCERAOAVxg21gfFi73t7C0aaTVsI1g6af96G/g0T47xV8xauJ81ntm/3cDNnC6ka1G42eK9liabK4LQ4u0D6XlPIWCAEUJ5GC9mww5pyo1Q6mv6zq9cRhrTcTwOjuOvfq58/u1JRmg/QhvyVCItDOcFyzVZbkHmGJ9YMzWGKrvR8D68pxIBARxQOAG9Uac0NypJhYoNwAdZ/n1XEv4t2A4tccdPWiZGbArCr3kbJabSfOAZsF64sJHrJxfFQuxT3s+QauvnVH0UuTNoK0JP/BWZD7oXLLmW+v0DOIGaWNpqwL/OSmGCvtnpNzuMKt/1IOpST4yrRL3kxJFTxvfLCtgJtMOVrnzEiAKTWLt82136ie4bl+xNQ1wX2y8tQd88Cxzu04xJTJomp/cJBwo2xrXVwmnYsMANcPFvtoZcgpnjXxTCx1nq3Ta1UUl3bijtB0HR1i7rB4YbDpivUScXwDOB7j7aqDW2phvGQSCYRcPmb8u01jfM=
  - secure: Y4pMSKYz0gdFwwXDcpbINmvr3oTjounUuzF6YGLCXSoxjsloDm+3duTKzJ6wa4B3rIwqtCAVvW/qTB4MekCksPubMHNlyKcXmS5wZ/SzdShX7mHi1pSSLqjzQPa+yIY6PKSq+/bKlsf8Nk4T5uBdxEnexlj/yxECxylCtpC16rCnEhz/nbjCiYYb2kBKBGsOF79ZtaX85+lKNwc1XjFrssJKShT5jB0J+ltrX/kHBTJqIxX4RmU2ALjr3l7yftAXrbHk02bjtWgAX7HmKWCQl/JriIobnRNNcVTB17lGOOoxQUgr4eEwz4n8N+WakSWAfJLPI36Wb5XF9RWpJ2jCdLTMFSZyoVi6DcDJn9RXAWMy5mEWnx2/3b56EPQgN2DpJc1VN2slpMN8ZtmvnfLCUqiwFk/5ZLG9vJFpqGHb6pMTw8s+4eeJNHCDR+E17VPhfS/s1ogcVJdFT8KCRxbhCLUD88JQ+/kEQZN/FDc8lPbH7pC1KLkxtMyReGyvBYYrdRcDwqCluJo8El5g0LcDWnkZ7nBCtEO7wF6IheAXd2vnqvGHo5fAfKhD6O5Z6aIheI4dR34yOinIOeDkY6Paq6Tzch1AMzQ5XxbdKLCOwY7ElAmiH56B5zyYP4mgWociswafGFpE13+rcG29Zl5smCmpFkBHH5U1v4PEiyCkQNM=
  - secure: BDvsoKI/H/wQmA/FMAtK7Y3AkY7lZ50Uyug63aASMD7amEQZYZd98IWuN+gRpAJdFPbXEPdTYwB38IWQaQ1X48waTWefGW8y0BOXDYA6CY2fLDO0EBCGjchFv6Ex6n6Xu1bWQw4aXS9Oj2OtSyLUH7lHouR58RWsun4Uc22n08eEHgOxzxrmaV24S6Di4So69CS6j64a89b6gtqfmXLWF0mEoocmnn7xUkEjfOHDX8CZ8UZp4cjLT7eDC1qJSFg3/y7WCYw3wlG0hylbnb/3BjBELToD2GBt5Osnl/0VmFspD14QybmiPjfE8D5X+CcOKeLxRUvNpZ0Yx0SZKdtVrgdQjw7Cgg1HEdQejNhvn6LzFMBe+b+a3bL27TZleacdGQs/UASxZyoiC34kfKoclLFjDZcyJNj8DAGKluc7/t8xidooOlvcrYoYDn79ewq7WK1xNBGEPe3JUleB9qg0k4lwZhLFMdNv3t7zbOpy379vYJj5VZk+AOOJTR6IKwHuV3GJulsmqyBvyqC3ratUL2UxgHyVSZYIS/eRkJDReNvXOQ5rWGIg+eV1MJAz8qHmsvUDiARwmA8zFkg9rssS7Bw6RC1plLmyXjGFKm5rmor7v9Sad0eFEtfVZ9apOaW+bJZ4Bb5gCpRjyHtas91tDHkScuPyZq3PplGqHpF8wEQ=
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
